# Main tmux config 
source-file ~/.config/tmux/modules/core.conf
source-file ~/.config/tmux/modules/panes.conf
source-file ~/.config/tmux/modules/copy.conf
source-file ~/.config/tmux/modules/ui.conf
source-file ~/.config/tmux/modules/tools.conf
