bind c new-window
bind v split-window -h
bind s split-window -v
bind x kill-pane
bind X kill-window

bind S choose-session
bind W choose-window
bind P choose-tree -Z

bind r source-file ~/.tmux.conf \; display "Reloaded!"
